- src/procproperties.cpp
On NetBSD, HZ tick can be retrieved same as OpenBSD.
> procproperties: Fix on NetBSD

- src/prettytable.cpp
fixes the huge icon of ```mate-sensors-applet``` process in LMDE 2
adapted from
https://git.gnome.org/browse/gnome-system-monitor/commit/?id=5480731230f9c6849fbf0aea1288b18bc9e62480
@clefebvre @raveit65 please test for any possible regressions
Latest comments at https://bugzilla.gnome.org/738467 say something about that bug striking again... but upstream code is a bit different. I can test it with ```mate-sensors-applet``` running only with GTK+ 3.14, so I'm curious how things are with more recent versions...
> process table: force icon size on loading

- src/load-graph.cpp
inspired from:
https://git.gnome.org/browse/gnome-system-monitor/commit/?id=a2d7fc1
> GTK3: don't use deprecated gtk_style_context_get_font

- src/disks.cpp
- src/lsof.cpp
- src/memmaps.cpp
- src/openfiles.cpp
- src/procproperties.cpp
- src/proctable.cpp
taken from:
https://git.gnome.org/browse/gnome-system-monitor/commit/?id=7fefa84
> GTK3: Drop use of deprecated treeview API. gtk_tree_view_set_rules_hint

- src/procdialogs.cpp
* Setting an adjustment with non-zero page size is deprecated
taken from:
https://git.gnome.org/browse/gnome-system-monitor/commit/?id=9ff48dc
> Fixed adustments to only be set with a page_size of 0

- src/procman_gksu.cpp
This will avoid crashing when trying to kill/renice another user's process. We can't load symbols from libgksu2.so anymore as m-s-m is GTK+3 only now.
How to test: select "All Processes" in View menu, then right-click on another user's process and try to renice it. You should see gksu dialog appearing. Well, you can try testing it with kill as well, but that's at your own risk. :smile:
@flexiondotorg @clefebvre @raveit65 @posophe @XRevan86 @willysr @obache 
Note: if m-s-m package in your distros depends on/recommends/suggests ```libgksu2```, it should be changed to ```gksu``` after this.
> run gksu binary instead of loading libgksu2.so (which is GTK+2 only)

- Makefile.am
- configure.ac
- org.mate.mate-system-monitor.policy.in.in
- po/POTFILES.in
- po/POTFILES.skip
- src/Makefile.am
- src/procdialogs.cpp
- src/procman_pkexec.cpp
- src/procman_pkexec.h
- tools/Makefile.am
- tools/msm_execute_helper.c
closes https://github.com/mate-desktop/mate-system-monitor/issues/85
try pkexec before trying gksu for killing other users' processes
or renicing a process. actual kill and renice commands are launched
via helper tool (see discussion at https://bugzilla.gnome.org/491462).
code is ported from gnome-system-monitor with some changes (e.g. helper
tool code is in tools/ dir instead of scripts/ - it's not a script).
for reference - relevant upstream commits:
https://git.gnome.org/browse/gnome-system-monitor/commit/?id=ccbff2a4293e43d6ea24fbf13477b10f58cd5212
https://git.gnome.org/browse/gnome-system-monitor/commit/?id=2b4308d9fc2b2e367030629e79b531c4f9ae3d0a
https://git.gnome.org/browse/gnome-system-monitor/commit/?id=971b3c704dea49b22c1038f200933c5b3b35ece1 …
> add pkexec support

- src/procman.cpp
This commit reverts:
https://github.com/mate-desktop/mate-system-monitor/commit/6d94559673232a1dc01d16eacbe2028aae175d07
And it applies an alternative to fix the deprecated functions:
gdk_screen_width
gdk_screen_height
> WidthOfScreen and HeightOfScreen implementation

- src/procman.cpp
without the PR:
```
if (msg != NULL) {
...
...
} else
timestamp = strtoul(msg, NULL, 0);
```
`msg` works as `NULL`, I think if this line is called, it makes a `Segmentation fault`, it is useless, so I removed it
NOTE: I think this warning was introduced by the commit https://github.com/mate-desktop/mate-system-monitor/commit/120ef9172463db2778b4790baa8ba7ae650aa247
> procman.cpp: Fix build warning: argument 1 null where non-null expected

- src/gsm_color_button.c
- src/gsm_color_button.h
Fixes the issue with GLib >= 2.58, list of modified files:
- src/gsm_color_button.c
- src/gsm_color_button.h
> Avoid compile warning for g_type_class_add_private

- src/interface.cpp
It's the context menu in process tab.
Works for me with mouse and keyboard events.
Please test.
> interface: avoid deprecated gtk_menu_popup

- src/callbacks.cpp
Note that GTK+ sets a default title of _("About %s") on the dialog
window (where %s is replaced by the name of the application, but
in order to ensure proper translation of the title, applications
should set the title property explicitly when constructing a
GtkAboutDialog
https://developer.gnome.org/gtk3/stable/GtkAboutDialog.html
> Ensure proper translation of the about dialog title

- src/sysinfo.cpp
```sh
$ cat os-release
NAME="openSUSE Tumbleweed"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20190314"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20190314"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```
> Fix openSUSE Tumbleweed rolling release info

- help/C/index.docbook
**Changes**
- How to start MATE System Monitor.
- Add information about four more fields that are shown in "memory maps" dialog.
- Add information about the rest of the "information fields" in the "Preferences" of "processes".
- Add "File Systems" tab in "Preferences" section and describe configuration options.
- Remove guidelines for changing background color in "Resource" tab and update guidelines for changing graph colors.
- Update that ending and terminating a process and opening "memory maps" can also be done by right-clicking on a process.
> update help with more information and some corrections

- src/callbacks.cpp
It also fixes the properties order to show properly the window title localized (l10n).
https://developer.gnome.org/gtk3/stable/GtkAboutDialog.html#GtkAboutDialog--program-name
> gtk3: use “program-name” property in gtk_show_about_dialog

- src/sysinfo.cpp
Arch Linux is a rolling release distribution.
Test:
- Backup /etc/os-release file
- Replace the content of /etc/os-release file
- Launch mate-system-monitor
- Select System tab
- Close mate-system-monitor
- Restore /etc/os-release file
```shell
$ cat ~/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```
After:
Arch Linux Real Screenshot (makepkg/pacman -U):
> Show 32/64-bit Version intead of release for Arch Linux in System tab

- src/sysinfo.cpp
Applied patch:
https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/components/desktop/mate/mate-system-monitor/patches/01-zfs.patch
Fixes #120
OpenIndiana Before:
OpenIndiana After:
FreeBSD Before:
FreeBSD After:
Ubuntu Before:
Ubuntu After:
> Show available disk space in ZFS

- src/sysinfo.cpp
@rbuj thanks! ( https://github.com/mate-desktop/mate-system-monitor/pull/140#issuecomment-473723361 )
before:
later:
> sysinfo: show debian version

- src/org.mate.system-monitor.gschema.xml.in
With this modification of  src/org.mate.system-monitor.gschema.xml.in, mate-system-monitor is able to support 32 CPU-colors. 
Fixes #145 
I'd say because of the increasing popularity of systems with many cores (e.g. AMD Epyc and Threadripper), mate-system-monitor should support more than 32 cores. But I can only append more CPU-color definitions to src/org.mate.system-monitor.gschema.xml.in. I don't know if this is a proper solution.
> Support 32 processors correctly

- src/Makefile.am
- src/procman_pkexec.cpp
- src/sysinfo.cpp
based on https://gitlab.gnome.org/GNOME/gnome-control-center/blob/master/panels/info/cc-info-overview-panel.c
Close #150
Screenshot (gnome-session):
Edit:
Change "GPU:" label to "Graphics:"
Screenshot (mate session):
Requires mate-desktop/mate-session-manager#203
> Show GPU info on the System tab

- src/procman.cpp
G_VARIANT_TYPE ("ai") = array of integers
Test: Change the columns order in Processes tab, run:
$ dconf read /org/mate/system-monitor/proctree/columns-order
It removes clang analizer warning: Cast from non-struct type to struct type
> procman: Use G_VARIANT_TYPE ("ai") instead of G_VARIANT_TYPE_ARRAY

- src/sysinfo.cpp
The member function '::SysInfo::get_os_type' can be static,
since it is not attached to any particular object, no 'this'
instance is passed to the function.
> Make SysInfo::get_os_type a static function

- help/C/index.docbook
Adds information regarding the new disk I/O feature that was added in PR #154 in the manual, on "Usage" and "Preferences" section.
> add disk I/O info on usage and prefs section

- src/proctable.cpp
Fixes `cppcheck` warnings:
```
[src/proctable.cpp:521]: (style) The scope of the variable 'column' can be reduced.
[src/proctable.cpp:238] -> [src/proctable.cpp:505]: (style) Local variable column shadows outer variable
[src/proctable.cpp:238] -> [src/proctable.cpp:511]: (style) Local variable column shadows outer variable
[src/proctable.cpp:238] -> [src/proctable.cpp:521]: (style) Local variable column shadows outer variable
```
> proctable: cppcheck: Local variable 'column' shadows outer variable

- .travis.yml
- configure.ac
- src/Makefile.am
- tools/Makefile.am
- It adds WARN_CFLAGS to CFLAGS, and WARN_CXXLAGS to CXXFLAGS
- By default, --enable-cxx-warnings=yes --enable-compile-warnings=yes
- It prints the warning flags in configure summary
Tests:
```
$ ./autogen.sh --enable-cxx-warnings=no --enable-compile-warnings=no
$ ./autogen.sh --enable-cxx-warnings=no --enable-compile-warnings=yes
$ ./autogen.sh --enable-cxx-warnings=yes --enable-compile-warnings=no
$ ./autogen.sh --enable-cxx-warnings=yes --enable-compile-warnings=yes
```
```
$ make clean && make AM_DEFAULT_VERBOSITY=1
```
It requires https://github.com/mate-desktop/mate-common/pull/30
> Use MATE_COMPILE_WARNINGS and MATE_CXX_WARNINGS macros

- src/gsm_color_button.c
Fixes the warnings:
```
gsm_color_button.c:75:13: warning: redundant redeclaration of 'gsm_color_button_class_intern_init' [-Wredundant-decls]
gsm_color_button.c:76:13: warning: redundant redeclaration of 'gsm_color_button_class_init' [-Wredundant-decls]
gsm_color_button.c:77:13: warning: redundant redeclaration of 'gsm_color_button_init' [-Wredundant-decls]
```
> gsm_color_button: avoid redundant redeclarations

- src/procdialogs.cpp
`find . \( -name '*.h' -o -name '*.cpp' \) -exec sed -i 's/[[:space:]]*$//' {} \;`
> procdialogs: Remove trailing spaces

- src/iconthemewrapper.cpp
- src/iconthemewrapper.h
- src/prettytable.cpp
- src/prettytable.h
based on https://github.com/GNOME/gnome-system-monitor/commit/97fb0b3e3b27b0a26488df5e4e2612ce79f81d53
> pretty-table: prefer GIO to get application icons

- src/gsm_color_button.c
```
gsm_color_button.c:954: warning: macro "__GSM_COLOR_BUTTON_C__" is not used [-Wunused-macros]
954 | #define __GSM_COLOR_BUTTON_C__
|
```
> gsm_color_button: macro "__GSM_COLOR_BUTTON_C__" is not used

- src/smooth_refresh.cpp
```
smooth_refresh.cpp: In member function 'unsigned int SmoothRefresh::get_own_cpu_usage()':
/usr/include/glib-2.0/glib/gmacros.h:813:63: warning: comparison of unsigned expression in '< 0' is always false [-Wtype-limits]
813 | #define CLAMP(x, low, high)  (((x) > (high)) ? (high) : (((x) < (low)) ? (low) : (x)))
|                                                           ~~~~^~~~~~~
smooth_refresh.cpp:37:13: note: in expansion of macro 'CLAMP'
37 |     usage = CLAMP(usage, 0, 100);
|             ^~~~~
```
> smooth_refresh: comparison of unsigned expression in '< 0' is always false

- src/openfiles.cpp
```
openfiles.cpp:122:84: warning: ‘void* g_memdup(gconstpointer, guint)’ is deprecated: Use 'g_memdup2' instead [-Wdeprecated-declarations]
122 |                         COL_OPENFILE_STRUCT, g_memdup(openfiles, sizeof(*openfiles)),
|                                                                                    ^
In file included from /usr/include/glib-2.0/glib.h:82,
from /usr/include/glib-2.0/glib/gi18n.h:21,
from openfiles.cpp:3:
/usr/include/glib-2.0/glib/gstrfuncs.h:257:23: note: declared here
257 | gpointer              g_memdup         (gconstpointer mem,
|                       ^~~~~~~~
memmaps.cpp: In member function ‘std::string {anonymous}::InodeDevices::get(guint64)’:
```
> openfiles: g_memdup is dreprecated from glib 2.68

- configure.ac
- src/Makefile.am
- src/prettytable.cpp
- src/prettytable.h
- src/procman-app.cpp
- src/procman.h
- src/procproperties.cpp
- src/proctable.cpp
therefore make libwnck optional (libwnck is x11 only)
see https://gitlab.gnome.org/GNOME/gnome-system-monitor/-/commit/3705931e307e87878f205b905eaa3f5daaffcf09
and https://gitlab.gnome.org/GNOME/gnome-system-monitor/-/commit/8c4d47d625661e848643ce564f63ed3ec1e83293
and https://gitlab.gnome.org/GNOME/gnome-system-monitor/-/commit/1ea64e9965bd6f1026f1167b692e7cc83c269be3
To enable libwnck support you need to compile with the `--enable-wnck` flag.
> add wayland support

- src/memmaps.cpp
warning:
```
memmaps.cpp:95:13: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
95 |             if (dev != dev64)
|             ^~
memmaps.cpp:98:17: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
98 |                 Map::iterator it(this->devices.find(dev));
|                 ^~~
```
> memmaps: fix warning -Wmisleading-indentation

- src/interface.cpp
Use a responsive design for listing CPUs usage in resources tab.
closes #232
> interface: use a flowbox instead of a grid for CPUs usage container

- src/gsm_color_button.c
- tools/msm_execute_helper.c
[test.webm](https://user-images.githubusercontent.com/10171411/183305860-784ab3f3-87f2-469b-9502-35bd4cfa8794.webm)
```
msm_execute_helper.c:8:51: warning: implicit conversion changes signedness: 'int' to 'gsize' (aka 'unsigned long') [-Wsign-conversion]
gchar **argv_modified = g_new0 (gchar *, argc + 1);
~~~~~~~~~~~~~~~~~~~~~~^~~~
--
msm_execute_helper.c:9:34: warning: implicit conversion changes signedness: 'int' to 'unsigned long' [-Wsign-conversion]
memcpy (argv_modified, argv, argc * sizeof (char*));
^~~~ ~
```
```
gsm_color_button.c:563:30: warning: implicit conversion turns floating-point number into integer: 'gdouble' (aka 'double') to 'guint16' (aka 'unsigned short') [-Wfloat-conversion]
dropped[0] = priv->color.red;
~ ~~~~~~~~~~~~^~~
gsm_color_button.c:564:30: warning: implicit …
```
> Fix conversion warnings

- meson.build
With  mate-system-monitor 1.27.0 and meson version 0.63.3 we get
` meson.build:1:0: ERROR: project got unknown keyword arguments "url"`
Remove the offending URL line from meson.build to fix this
> Fix meson configuration failure on URL keyword 

- configure.ac
contrary to help string (--disable-systemd) systemd was not enabled by default since enable_systemd was set to `no` if no option was passed. do enable it but use `auto` mode by default: use systemd if available but continue if it's missing. enforcing systemd can be ecomplished with --enable-systemd.
> build: do enable systemd by default (but don't force it)
